### PR TITLE
Update pattern-matching-for-java.md

### PR DESCRIPTION
**Pull request by davidalayachew**
---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * @yannicklamprecht (no known openjdk.org user name / role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/amber-docs.git pull/21/head:pull/21` \
`$ git checkout pull/21`

Update a local copy of the PR: \
`$ git checkout pull/21` \
`$ git pull https://git.openjdk.org/amber-docs.git pull/21/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21`

View PR using the GUI difftool: \
`$ git pr show -t 21`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/amber-docs/pull/21.diff">https://git.openjdk.org/amber-docs/pull/21.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/amber-docs/pull/21#issuecomment-1644686971)

### CODE REVIEW

**Review by yannicklamprecht — APPROVED** [review]

**Comment by GavinBierman** [comment]
No problem - let's try again :-)

**Pull request closed without merging**
